### ISSUE TITLE
tests /  database

### ISSUE THREAD

**Issue by hitz** [CanDIG/rnaget_service#32]
Hi -
I am looking to fork this for the ENCODE/Roadmap RNA-get service. Do the tests run if you don't have a database?   Is there somewhere I can grab a sample database, or do I have to make one.

**Comment by ljdursi** [comment]
Hi, Ben - the original developer of this tool has just moved on, I’ll assign myself the task of getting this answered for you.

**Comment by ljdursi** [comment]
Hi, @hitz - sorry for the delay in responding this.  Yes, the tests are just unit tests and run correctly without a database.  As part of the tests it generates a simple sqlite3 database.

**Comment by hitz** [comment]
yeah, I found it it's named operations.db.   That test works fine, but I am having trouble with the dredd tests.  Possibly they were made prospectively?  So that, when they all pass the work is done?

**Comment by ljdursi** [comment]
Ah - maybe those should be gotten rid of, the dredd tests aren't currently being run by the test suite (which you can run just using `tox`).  I'll see if I can check to see if there's anything worth getting to work there or if it's just holdovers from the projects that were used as a template for this one.

**Comment by hitz** [comment]
They are run via "make tests" or "py.test".   I actually didn't try tox.

**Comment by ljdursi** [comment]
I'w updated `make tests` to only run the tests/test_operations.py, which is all that currently works.
